services:
  phdmanager.traefik:
    image: traefik:v3.1.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  phdmanager.db:
    image: postgres:17.0
    environment:
      POSTGRES_PASSWORD: phdmanager
      POSTGRES_DB: phdmanager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  phdmanager.web:
    image: ${DOCKER_REGISTRY-}phdmanagerweb
    build:
      context: .
      dockerfile: PhDManager.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    labels:
      - traefik.enable=true
      - traefik.http.routers.webapp.rule=Host(`localhost`)
    depends_on:
      - phdmanager.api
    networks:
      - app-network

  phdmanager.api:
    image: ${DOCKER_REGISTRY-}phdmanagerapi
    build:
      context: .
      dockerfile: PhDManager.Api/Dockerfile
    ports:
      - "8180:8080"
      - "8181:8081"
    depends_on:
      - phdmanager.db
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge