CREATE TABLE "users" (
  "user_id" integer PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "display_name" varchar NOT NULL,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "role" varchar NOT NULL DEFAULT 'User',
  "first_login" timestamp
);

CREATE TABLE "students" (
  "student_id" integer PRIMARY KEY,
  "study_program_id" varchar
);

CREATE TABLE "theses" (
  "thesis_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "year" integer NOT NULL,
  "title" varchar NOT NULL,
  "description" text,
  "student_id" integer,
  "supervisor_id" integer NOT NULL
);

CREATE TABLE "subjects" (
  "subject_id" varchar PRIMARY KEY,
  "name" varchar NOT NULL,
  "semester" varchar NOT NULL,
  "credits" integer NOT NULL
);

CREATE TABLE "study_programs" (
  "study_program_id" varchar PRIMARY KEY,
  "name" varchar NOT NULL
);

ALTER TABLE "students" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("user_id");

ALTER TABLE "students" ADD FOREIGN KEY ("study_program_id") REFERENCES "study_programs" ("study_program_id");

ALTER TABLE "theses" ADD FOREIGN KEY ("student_id") REFERENCES "students" ("student_id");

ALTER TABLE "theses" ADD FOREIGN KEY ("supervisor_id") REFERENCES "users" ("user_id");

CREATE TABLE "subjects_study_programs" (
  "subjects_subject_id" varchar,
  "study_programs_study_program_id" varchar,
  PRIMARY KEY ("subjects_subject_id", "study_programs_study_program_id")
);

ALTER TABLE "subjects_study_programs" ADD FOREIGN KEY ("subjects_subject_id") REFERENCES "subjects" ("subject_id");

ALTER TABLE "subjects_study_programs" ADD FOREIGN KEY ("study_programs_study_program_id") REFERENCES "study_programs" ("study_program_id");


CREATE TABLE "students_subjects" (
  "students_student_id" integer,
  "subjects_subject_id" varchar,
  PRIMARY KEY ("students_student_id", "subjects_subject_id")
);

ALTER TABLE "students_subjects" ADD FOREIGN KEY ("students_student_id") REFERENCES "students" ("student_id");

ALTER TABLE "students_subjects" ADD FOREIGN KEY ("subjects_subject_id") REFERENCES "subjects" ("subject_id");

